/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lcdrefactor.view;

import javax.swing.JOptionPane;
import lcdrefactor.logic.LCDRefactor;

/**
 *
 * @author Jonathan
 */
public class LCDDisplay extends javax.swing.JFrame {

    /**
     * Creates new form LCDDisplay
     */
    public LCDDisplay() {
        initComponents();
        Display.setEditable(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTextArea();
        espacio = new javax.swing.JLabel();
        size = new javax.swing.JLabel();
        number = new javax.swing.JLabel();
        campo_espacio = new javax.swing.JTextField();
        campo_size = new javax.swing.JTextField();
        campo_number = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        print_button = new javax.swing.JButton();
        button_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LCD");

        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Display.setColumns(20);
        Display.setFont(new java.awt.Font("Lucida Console", 0, 13)); // NOI18N
        Display.setRows(5);
        jScrollPane1.setViewportView(Display);

        espacio.setText("Espacio entre digitos:");

        size.setText("Tamaño del número:");

        number.setText("Número:");

        campo_espacio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_espacioKeyTyped(evt);
            }
        });

        campo_size.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_sizeKeyTyped(evt);
            }
        });

        campo_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campo_numberKeyTyped(evt);
            }
        });

        add_button.setText("Agregar número");
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });

        print_button.setText("Imprimir");
        print_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_buttonMouseClicked(evt);
            }
        });

        button_reset.setText("Reset");
        button_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_resetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(espacio, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_espacio)
                            .addComponent(campo_size)
                            .addComponent(print_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(campo_number, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_button)))))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espacio)
                    .addComponent(campo_espacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number)
                    .addComponent(campo_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_reset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
        String numero = campo_number.getText();
        String tamaño = campo_size.getText();
        if(numero.isEmpty() || tamaño.isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el número y su tamaño.","ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }else{
            LCDRefactor.addNumber(tamaño+","+numero);
            JOptionPane.showMessageDialog(null, "Número agregado con éxito","INFORMACIÓN", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_add_buttonMouseClicked

    private void print_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_buttonMouseClicked
        String space = campo_espacio.getText();
        if(space.isEmpty()){
            JOptionPane.showMessageDialog(null, "Rellene el espacio entre dígitos.","ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }else{
            String response = LCDRefactor.runNumericValidation(space);
            if (!response.equalsIgnoreCase("OK")) {
                JOptionPane.showMessageDialog(null, response, "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            }else{
                campo_espacio.setEnabled(false);
                campo_size.setEnabled(false);
                campo_number.setEnabled(false);
                print_button.setEnabled(false);
                add_button.setEnabled(false);
                LCDRefactor.runProcess();
            }
        }
    }//GEN-LAST:event_print_buttonMouseClicked
    
    public static void show_number(String segmento){
        Display.append(segmento);
    }
    
    private void campo_espacioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_espacioKeyTyped
        Consume(evt);
    }//GEN-LAST:event_campo_espacioKeyTyped

    private void campo_sizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_sizeKeyTyped
        Consume(evt);
    }//GEN-LAST:event_campo_sizeKeyTyped

    private void campo_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_numberKeyTyped
        Consume(evt);
    }//GEN-LAST:event_campo_numberKeyTyped

    private void button_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_resetMouseClicked
        campo_espacio.setEnabled(true);
        campo_size.setEnabled(true);
        campo_number.setEnabled(true);
        print_button.setEnabled(true);
        add_button.setEnabled(true);
        
        campo_espacio.setText("");
        campo_size.setText("");
        campo_number.setText("");
        
        Display.setText("");
        
        LCDRefactor.clearData();
    }//GEN-LAST:event_button_resetMouseClicked
    
    private void Consume(java.awt.event.KeyEvent evt){
        char c = evt.getKeyChar();
        if(c < '0' || c > '9'){
            evt.consume();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LCDDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LCDDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LCDDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LCDDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LCDDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea Display;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton add_button;
    private javax.swing.JButton button_reset;
    private javax.swing.JTextField campo_espacio;
    private javax.swing.JTextField campo_number;
    private javax.swing.JTextField campo_size;
    private javax.swing.JLabel espacio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel number;
    private javax.swing.JButton print_button;
    private javax.swing.JLabel size;
    // End of variables declaration//GEN-END:variables
}
